Upgrade to steal 1
stealjs/steal-sass pull request #18
Opened 2017-03-17 13:28 UTC by ilyavf

This fixes the reported issue: https://github.com/stealjs/steal-sass/issues/17

2017-03-17 13:43 UTC, phillipskevin requested changes

2017-03-17 13:43 UTC, phillipskevin commented on package.json
> +  "steal": {
You should leave this as `system` so that it will still work with steal 0.16.

2017-03-17 14:10 UTC, ilyavf commented on package.json
> +  "steal": {
@phillipskevin Fixed.

2017-03-17 14:12 UTC, phillipskevin approved these changes

2017-03-21 19:12 UTC, matthewp commented
I don't maintain this package, my approval is not needed. If anyone wants it, I'll give you npm access.

2017-03-31 20:15 UTC, merged